
spring:
  profiles:
    default: local

  datasource:
#    url: jdbc:h2:mem:~/wirebarley
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:mysql://localhost:3306/wirebarley
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

